-- MySQL Script generated by MySQL Workbench
-- Fri Sep 10 16:30:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `tipoIdentificacion` VARCHAR(45) NOT NULL,
  `identificacion` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuarios`),
  UNIQUE INDEX `idUsuarios_UNIQUE` (`idUsuarios` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Productos` (
  `idProductos` INT NOT NULL AUTO_INCREMENT,
  `nombreProducto` VARCHAR(45) NOT NULL,
  `unidadMedida` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `cantidad` INT NOT NULL,
  `iva` FLOAT NOT NULL,
  `precioCompra` DOUBLE NOT NULL,
  `precioVenta` DOUBLE NULL,
  PRIMARY KEY (`idProductos`),
  UNIQUE INDEX `idInventario_UNIQUE` (`idProductos` ASC) VISIBLE,
  UNIQUE INDEX `nombreProducto_UNIQUE` (`nombreProducto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entradas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entradas` (
  `idEntradas` INT NOT NULL AUTO_INCREMENT,
  `idProductosEntradas` INT NOT NULL,
  `fechaIngreso` DATE NOT NULL,
  `idProveedor` INT NOT NULL,
  `cantidadCompra` INT NOT NULL,
  PRIMARY KEY (`idEntradas`),
  UNIQUE INDEX `idEntradas_UNIQUE` (`idEntradas` ASC) VISIBLE,
  INDEX `UsuarioEntradas_idx` (`idProveedor` ASC) VISIBLE,
  INDEX `EntradaProductos_idx` (`idProductosEntradas` ASC) VISIBLE,
  CONSTRAINT `UsuarioEntradas`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `EntradaProductos`
    FOREIGN KEY (`idProductosEntradas`)
    REFERENCES `mydb`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tenderos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tenderos` (
  `idTenderos` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `idUsuariosTenderos` INT NOT NULL,
  PRIMARY KEY (`idTenderos`),
  UNIQUE INDEX `idTenderos_UNIQUE` (`idTenderos` ASC) VISIBLE,
  INDEX `usuariosTenderos_idx` (`idUsuariosTenderos` ASC) VISIBLE,
  CONSTRAINT `usuariosTenderos`
    FOREIGN KEY (`idUsuariosTenderos`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Salidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Salidas` (
  `idSalidas` INT NOT NULL AUTO_INCREMENT,
  `fechaSalida` DATE NOT NULL,
  `idComprador` INT NOT NULL,
  `idTendero` INT NOT NULL,
  `totalFactura` DOUBLE NOT NULL,
  PRIMARY KEY (`idSalidas`),
  UNIQUE INDEX `idSalidas_UNIQUE` (`idSalidas` ASC) VISIBLE,
  INDEX `usuarioSalida_idx` (`idComprador` ASC) VISIBLE,
  INDEX `tenderosSalidas_idx` (`idTendero` ASC) VISIBLE,
  CONSTRAINT `usuarioSalida`
    FOREIGN KEY (`idComprador`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tenderosSalidas`
    FOREIGN KEY (`idTendero`)
    REFERENCES `mydb`.`Tenderos` (`idTenderos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProductoSalida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProductoSalida` (
  `idProductoSalida` INT NOT NULL,
  `idProductos` INT NOT NULL,
  `valorUnitarioVenta` DOUBLE NOT NULL,
  `valorUnitarioCompra` DOUBLE NOT NULL,
  `iva` FLOAT NOT NULL,
  `idSalidas` INT NOT NULL,
  `cantidades` DOUBLE NOT NULL,
  PRIMARY KEY (`idProductoSalida`),
  INDEX `productoSalida_idx` (`idProductos` ASC) VISIBLE,
  INDEX `salidasProducto_idx` (`idSalidas` ASC) VISIBLE,
  CONSTRAINT `productoSalida`
    FOREIGN KEY (`idProductos`)
    REFERENCES `mydb`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `salidasProducto`
    FOREIGN KEY (`idSalidas`)
    REFERENCES `mydb`.`Salidas` (`idSalidas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
